### PR TITLE
fix "Cannot read properties of undefined (reading 'startsWith')"

### LINKED ISSUE #11: Module has error under Companion 4.0
Module works great (thank you BTW for making it), under 3.54 but doesn't seem to function under Companion 4.  Inside the Setting window under Module, all it says is:

Something went wrong:
undefined is not an object (evaluating 'e.formattype.startsWith')

so far, the functionality seems to work, but you can't set anything in the settings page because of the error

### PR DESCRIPTION
**Pull request by h07d0q**
fixes https://github.com/bitfocus/companion-module-generic-dataentry/issues/11
also included and ran format/prettier

### CODE REVIEW

File: main.js [hunk 1]
```diff
@@ -252,7 +252,7 @@ class DataEntryInstance extends InstanceBase {
 				default: '*',
 				useVariables: true,
 				isVisible: (opt) => {
-					return opt.formattype.startsWith('ecma')
+					return !!opt && typeof opt.formattype === 'string' && opt.formattype.startsWith('ecma')
```
Comment (peternewman) [inline main.js]: From the hide whitespace view, it looks like this is the actual fix? https://github.com/bitfocus/companion-module-generic-dataentry/pull/12/files?diff=unified&w=1

For the future it may be worth separating the prettification commit from any code changes to simplify review.

File: .yarn/install-state.gz
Comment (peternewman) [inline .yarn/install-state.gz:1]: This wants removing and .gitignoring:
https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

Comment (peternewman) [reply .yarn/install-state.gz:1]: There's an updated .gitignore from the template you could pull in:
https://github.com/bitfocus/companion-module-template-js/blob/main/.gitignore

File: main.js (hunk 1 above)
Comment (thedist) [inline main.js]: If the PR aims to make changes to `isVisible`, which is deprecated, why not just spend the time now to use `isVisibleExpression` instead?

File: main.js [hunk 2]
```diff
@@ -251,9 +241,7 @@ class DataEntryInstance extends InstanceBase {
 				width: 6,
 				default: '*',
 				useVariables: true,
-				isVisible: (opt) => {
-					return !!opt && typeof opt.formattype === 'string' && opt.formattype.startsWith('ecma')
-				},
+				isVisibleExpression: `$(options:formattype) == 'ecmaauto' || $(options:formattype) == 'ecmastring' || $(options:formattype) == 'ecmanumber' || $(options:formattype) == 'ecmadate' || $(options:formattype) == 'ecmatime' || $(options:formattype) == 'ecmabool'`,
```
Comment (bryce-seifert) [inline main.js]: Perhaps it could be possible to use `includes($(options:formattype), "ecma")`, to make this a little cleaner?

File: package.json [hunk 3]
```diff
@@ -12,13 +12,14 @@
 		"url": "git+https://github.com/bitfocus/companion-module-generic-dataentry.git"
 	},
 	"dependencies": {
-		"@companion-module/base": "~1.5.1",
+		"@companion-module/base": "^1.13.2",
```
Comment (bryce-seifert) [inline package.json]: Just noting, that updating this to 1.13 will require users to be on Companion 4.1, which just came out recently.
https://github.com/bitfocus/companion-module-base?tab=readme-ov-file#supported-versions-of-this-library

It might be worth making this 1.12 so that 4.0 users can get the fix
